# Site settings
title: Xtext Gradle Plugins
author: The Xtext Team
email: xtext@typefox.io
description: >
  Xtext is a framework for development of programming languages and domain-specific languages.
baseurl: "/xtext-gradle-plugin"
url: "http://xtext.org"
twitter_username: xtext
github_username:  xtext

# Build settings
markdown: kramdown
